export const firstCategories = [
  {
    title: "Toudoum",
    theme: "FilmsCultes",
    imageUrl: require("../../assets/images/toudoum.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#313131",
  },
  {
    title: "Super-héros",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/superhero.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#03987D",
  },
  {
    title: "Jeux vidéos",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/jeuxvideo.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#D5011D",
  },
  {
    title: "Répliques cultes",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/repliquescultes.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#7A4121",
  },
  {
    title: "Animaux",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/animaux.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#DFB472",
  },
  {
    title: "Années 80",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/annees80.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#4C5699",
  },

  {
    title: "Boissons",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/boissons.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#F2326C",
  },
  {
    title: "Animés",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/animes.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#313131",
  },
  {
    title: "Recettes",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/recettes.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#961B20",
  },
  {
    title: "Plage",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/plage.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#FFD2B5",
  },
  {
    title: "Inventions",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/inventions.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#728ADF",
  },
  {
    title: "Personnages historiques",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/persohistoriques.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#FFC42C",
  },
  {
    title: "Grand écran",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/grandecran.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#BE80E1",
  },
  {
    title: "Super-héros",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/superhero2.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#912320",
  },
  {
    title: "Méchants",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/mechants.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#333333",
  },
];

export const secondCategories = [
  {
    title: "Ecrivains",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/ecrivain.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "",
  },
  {
    title: "Acteurs",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/acteurs.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "",
  },
  {
    title: "Chansons",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/chanson.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "",
  },
  {
    title: "Emissions télé",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/emissiontv.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "",
  },
  {
    title: "Expressions françaises",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/expressionfrancaise.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "",
  },

  {
    title: "Football",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/football.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "",
  },
  {
    title: "Jeux de sociétés",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/jeudesociete.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "",
  },
  {
    title: "Mode",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/mode.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "",
  },
  {
    title: "Montagne",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/montagne.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "",
  },
  {
    title: "Moyen de transport",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/moyendetransports.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "",
  },
  {
    title: "Plantes & fleurs",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/plantes.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "",
  },
  {
    title: "Rap",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/rapgame.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "",
  },
  {
    title: "Sports",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/sport.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "",
  },
  {
    title: "Youtube",
    theme: "Gratuit",
    imageUrl: require("../../assets/images/youtube.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "",
  },
];

export const thirdCategories = [
  {
    title: "Animaux",
    theme: "Animaux",
    imageUrl: require("../../assets/images/animaux.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#DFB472F2",
  },
  {
    title: "Capitales du monde",
    theme: "CapitalesDuMonde",
    imageUrl: require("../../assets/images/expressionfrancaise.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#4C5699",
  },
  {
    title: "Films cultes",
    theme: "FilmsCultes",
    imageUrl: require("../../assets/images/grandecran.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#BE80E1",
  },
  {
    title: "Marques",
    theme: "Marques",
    imageUrl: require("../../assets/images/mode.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#FFC42C",
  },
  {
    title: "Montagne",
    theme: "Montagne",
    imageUrl: require("../../assets/images/montagne.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#728ADF",
  },
  {
    title: "Célébrités",
    theme: "Celebrites",
    imageUrl: require("../../assets/images/acteurs.png"),
    gameplay: "deviner",
    punchline: "",
    cardColor: "#313131",
  },
];
